repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-yaml
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.3.6
    hooks:
      - id: reorder-python-imports
        args: ['--py3-plus']
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        args: ['--line-length=120']
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.790
    hooks:
      - id: mypy
  - repo: https://github.com/doublify/pre-commit-clang-format
    rev: master
    hooks:
      - id: clang-format
