cc_test(
    name = "test",
    linkstatic = False,
    srcs = [
        "py_envoy_headers_test.cc",
    ],
    deps = [
        "//py_envoy_mobile/wrapper:lib",
        "@gtest//:gtest_main",
    ],
)
